### PR TITLE
completed html-forms exercise

### PR DESCRIPTION
**Pull request by mdoanle**
Screen Shot 2022-08-23 at 9 42 34 AM

### CODE REVIEW

**Comment by mdoanle** [comment]
Screen Shot 2022-08-23 at 9 42 17 AM

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Please rework your solution so that clicking the radio button / check box labels activates them. Also, only one radio button should be selectable at a time, so they all need the same `name` attribute.

**Comment by mdoanle** [comment]
Screen Shot 2022-08-23 at 10 06 37 AM

**Review by thebearingedge — CHANGES_REQUESTED** [review]
Ok, excellent the last change is to just put everything into one `<form>` element instead of multiple.

**Review by thebearingedge — APPROVED** [review]

**Pull request merged**
